### ISSUE TITLE
How to pass a channel / context like object to golang?

### ISSUE THREAD

**Issue by clmno** [asottile/setuptools-golang#99]
I would like to start a `go routine` from python but it should be closable. In golang we can use a simple concurrency pattern here - the [context pattern](https://go.dev/blog/context)

How do I acheive this?

Or a better question is
1. How to start and close a goroutine safely from python? What should the C.API be for this?

**Comment by asottile** [comment]
I believe you'd need to manage your goroutines entirely on the go side and won't really be able to interact with them from the python side -- mostly because the two concurrency models don't have an equivalent translation

Usually the expectation is a single direction message passing via arguments and return values and not bidirection or multidirection which would be required for goroutines

**Comment by clmno** [comment]
What happens when the python program ends? Will it also clear memory used by the golang shared library too?

My main concern is memory leak. I have a program that starts a lot of goroutines. And once the job is finished it ends them, one by one. But in a scenario where the pycode wants to shutdown will these goroutines still be running? Or will they be garbage collected? Or the OS kills them as the parent has died?

**Comment by asottile** [comment]
when a process ends the entire memory space is torn down -- doesn't matter if that memory originated from a shared object.

goroutines are "greenthreads" in that they're not actually "sub process" like so when their executor is torn down they are no longer running

**Comment by clmno** [comment]
Alright, awesome. Thanks you @asottile 
Great video, I'd never thought of using a go extension but you made it look so easy I couldn't resist
